PATH_TO_RETRO68=$(HOME)/Retro68-build/toolchain/m68k-apple-macos

.SUFFIXES:	.bin

CC=m68k-apple-macos-gcc
CXX=m68k-apple-macos-g++

INCPATH+= -I"../include"

LIBPATH = -L.. -L$(HOME)/tinygl/lib
#LIBS    = -lSDL2_test -lSDL2 -lm -lRetroConsole
#LIBS    = -lSDL2_test -lSDL2 -lm ../../macos8addons/libmacos8addons.a -lOpenGLLibrary
#LIBS    = -lSDL2_test -lSDL2 -lm ../../macos8addons/libmacos8addons.a -L$(HOME)/tinygl-main1/lib -lTinyGL -lagl -lgl
#LIBS    =  -lSDL2_test -lSDL2 -lm $(HOME)/Mesa-3.2.1/libmesa.a ../../macos8addons/libmacos8addons.a  $(HOME)/MacGLide-master/MacGLide/OpenGLide/libOpenGlide.a $(HOME)/MacGLide-master/MacGLide/Mac/libMac.a
#LIBS    = -lSDL2_test -lSDL2 -lm -lThreadsLib 
#LIBS    = -lSDL2_test -lSDL2 -lm -lInputSprocketLib -lDrawSprocketLib -lOpenGLLibrary ../../macos8addons/libmacos8addons.a  
LIBS    = -lSDL2_test -lSDL2 -lm -lInputSprocketLib -lDrawSprocketLib -lTinyGL ../../macos8addons/libmacos8addons.a  

#CFLAGS+= -DHAVE_SDL_TTF
#TTFLIBS = SDL2ttf.lib

#CFLAGS+= $(INCPATH) -D__MACOSCLASSIC__ -DSDL_MACOSCLASSIC_INPUTSPROCKET=1 -DSDL_MACOSCLASSIC_AGL=1 -DHAVE_OPENGL=1
CFLAGS+= $(INCPATH) -D__MACOSCLASSIC__ -DSDL_MACOSCLASSIC_INPUTSPROCKET=1 -DSDL_MACOSCLASSIC_TINYGL=1 -DHAVE_OPENGL=1

TARGETS = testatomic.bin testdisplayinfo.bin testbounds.bin testdraw2.bin \
          testdrawchessboard.bin testdropfile.bin testerror.bin testfile.bin \
          testfilesystem.bin testgamecontroller.bin testgeometry.bin testgesture.bin \
          testhittesting.bin testhotplug.bin testiconv.bin testime.bin testlocale.bin \
          testintersections.bin testjoystick.bin testkeys.bin testloadso.bin \
          testlock.bin testmessage.bin testoverlay2.bin testplatform.bin \
          testpower.bin testsensor.bin testrelative.bin testrendercopyex.bin \
          testrendertarget.bin testrumble.bin testscale.bin testsem.bin \
          testshader.bin testshape.bin testsprite2.bin testspriteminimal.bin \
          teststreaming.bin testthread.bin testtimer.bin testver.bin \
          testviewport.bin testwm2.bin torturethread.bin checkkeys.bin \
          checkkeysthreads.bin testmouse.bin testgles.bin testgles2.bin \
          controllermap.bin testhaptic.bin testqsort.bin testresample.bin \
          testaudioinfo.bin testaudiocapture.bin loopwave.bin loopwavequeue.bin \
          testsurround.bin testyuv.bin testgl2.bin testvulkan.bin testnative.bin \
          testaudiohotplug.bin testcustomcursor.bin testmultiaudio.bin \
          testoffscreen.bin testurl.bin

noninteractive = \
	testatomic.bin \
	testerror.bin \
	testfilesystem.bin \
	testkeys.bin \
	testlocale.bin \
	testplatform.bin \
	testpower.bin \
	testqsort.bin \
	testthread.bin \
	testtimer.bin \
	testver.bin

needs_audio = \
	testaudioinfo.bin \
	testsurround.bin

needs_display = \
	testbounds.bin \
	testdisplayinfo.bin

TESTS = $(noninteractive) $(needs_audio) $(needs_display)

# testautomation sources
TASRCS = testautomation.c \
	testautomation_audio.c testautomation_clipboard.c \
	testautomation_events.c testautomation_guid.c \
	testautomation_hints.c testautomation_joystick.c \
	testautomation_keyboard.c testautomation_log.c \
	testautomation_main.c testautomation_math.c \
	testautomation_mouse.c testautomation_pixels.c \
	testautomation_platform.c testautomation_rect.c \
	testautomation_render.c testautomation_rwops.c \
	testautomation_sdltest.c testautomation_stdlib.c \
	testautomation_subsystems.c testautomation_surface.c \
	testautomation_syswm.c testautomation_timer.c \
	testautomation_video.c

OBJS = $(TARGETS:.bin=.o)
COBJS = $(CSRCS:.c=.o)
TAOBJS = $(TASRCS:.c=.o)
TNOBJS = $(TNSRCS:.c=.o)


all: testutils.lib $(TARGETS)


.o.bin:
	$(CXX) -o $*.code.bin $< testutils.o testyuv_cvt.o ../src/main/macosclassic/SDL_main.o $(LIBPATH) $(LIBS)
	../../bin2app.sh $*

%.o : %.c
	@echo Compiling $<
	@$(CC) -o $@ -c $< $(CFLAGS)


# specials

#testautomation_stdlib.o: testautomation_stdlib.c
#	 $(CFLAGS) -wcd=201 -fo=$^@ $<

#testautomation.bin: $(TAOBJS)
#	 $(CC) $(LIBPATH) lib {$(LIBS)} op q op el file {$<} name $@


testutils.lib: testutils.o testyuv_cvt.o
#  wlib -q -b -n -c -pa -s -t -zld -ii -io $@ $<

check: .SYMBOLIC $(TESTS)
#  @set SDL_AUDIODRIVER=dummy
#  @set SDL_VIDEODRIVER=dummy
#  @copy ..\SDL2.dll .
#  @for .bin in ($(TESTS)) do .bin

check-quick: .SYMBOLIC $(TESTS)
#  @set SDL_TESTS_QUICK=1
#  @set SDL_AUDIODRIVER=dummy
#  @set SDL_VIDEODRIVER=dummy
#  @copy ..\SDL2.dll .
#  @for .bin in ($(TESTS)) do .bin

clean:
	rm -rf *.o *.err *.bin *.pef *.dsk *.bin *.APPL *.gdb .rsrc .finf
	rm -f testkeys testoverlay2 testscale testaudioinfo testlocale testvulkan testintersect ions testerror testviewport testcustomcursor testmessage testrendertarget testver test file testsurround testgl2 controllermap testmouse testplatform testhotplug testdisplay info testloadso loopwave testsem checkkeysthreads testresample testgamecontroller chec kkeys testshader testsensor testyuv testsprite2 testime testurl testshape testiconv te stgles teststreaming testtimer testatomic testoffscreen testwm2 testbounds testthread testgles2 testgeometry testspriteminimal testrumble torturethread testdraw2 testaudioh otplug testhittesting testjoystick testrelative testmultiaudio testpower testaudiocapt ure loopwavequeue testdropfile testfilesystem testqsort testdrawchessboard testnative testrendercopyex testlock testgesture testhaptic testgles testintersections testfile testaudiocapture testaudiohotplug checkkeys testdisplayinfo

distclean: clean
	rm -f *.bin *.lib
