# Makefile to build the classic MacOS SDL library
# (Based on AmigaOS4 Makefile)

PATH_TO_TOOLS=/opt/m68k-palm-elf

AR = m68k-palm-elf-ar
RANLIB = m68k-palm-elf-ranlib
CC = m68k-palm-elf-gcc
CXX = m68k-palm-elf-g++
STRIP = m68k-palm-elf-strip
#CRT ?= newlib
INSTALL_PATH ?=
CATCOMP = catcomp # TODO: is there a cross-compiler version?

#MACDATE = $(shell date +"%-d.%m.%Y")

#CFLAGS  = -mcrt=$(CRT) -gstabs -O3 -Wall -Werror -Wshadow -fPIC -fcommon -I./include -D__MACDATE__=\"$(MACDATE)\"
CFLAGS  = -Wall -Wshadow -I./include -D__PALMOS__ -DPALM_DEBUG -I$(PATH_TO_TOOLS)/include

TARGET_STATIC  = libSDL2.a
#TARGET_SHARED  = libSDL2-2.31.so
TESTLIB_STATIC = libSDL2_test.a
#PREFS_PROGRAM = SDL2

SOURCES = \
	./src/*.c \
	./src/atomic/*.c \
	./src/audio/*.c \
	./src/audio/disk/*.c \
	./src/audio/dummy/*.c \
	./src/cpuinfo/*.c \
	./src/events/*.c \
	./src/file/*.c \
	./src/haptic/*.c \
	./src/haptic/dummy/*.c \
	./src/joystick/*.c \
	./src/joystick/virtual/*.c \
	./src/libm/*.c \
	./src/locale/*.c \
	./src/locale/dummy/*.c \
	./src/main/palmos/*.c \
	./src/misc/*.c \
	./src/misc/dummy/*.c \
	./src/power/*.c \
	./src/render/*.c \
	./src/render/opengl/*.c \
	./src/render/opengles2/*.c \
	./src/render/software/*.c \
	./src/sensor/*.c \
	./src/sensor/dummy/*.c \
	./src/stdlib/*.c \
	./src/thread/*.c \
	./src/thread/palmos/*.c \
	./src/timer/*.c \
	./src/video/*.c \
	./src/video/offscreen/*.c \
	./src/video/yuv2rgb/*.c \

TESTLIB_SOURCES =./src/test/*.c

OBJECTS = $(shell echo $(SOURCES) | sed -e 's,\.c,\.o,g')
TESTLIB_OBJECTS = $(shell echo $(TESTLIB_SOURCES) | sed -e 's,\.c,\.o,g')
MAIN_OBJECT = src/main/palmos/SDL_main.o
ALL_OBJECTS = $(OBJECTS) $(TESTLIB_OBJECTS) $(MAIN_OBJECT) $(PREFS_OBJECT)
DEPS = $(ALL_OBJECTS:.o=.d)


all: info $(TARGET_STATIC) $(TARGET_SHARED) $(TESTLIB_STATIC) $(PREFS_PROGRAM)
	@echo All done
#	cp libSDL2.a src/main/dummy/SDL_main.o ..
#	cp include/*.h ../SDL2

info:
	@echo Compiler flags: $(CFLAGS)

debug: CFLAGS += -DDEBUG

debug: all

$(TESTLIB_STATIC): $(TESTLIB_OBJECTS)
	@echo Creating $@
	@$(AR) crv $@ $^
	@$(RANLIB) $@
	@$(AR) crv libSDL2main.a $(MAIN_OBJECT) 
	@$(RANLIB) libSDL2main.a


$(TARGET_STATIC): $(OBJECTS)
	@echo Creating $@
	@$(AR) crv $@ $^
	@$(RANLIB) $@

$(TARGET_SHARED): $(OBJECTS) $(MAIN_OBJECT)
	@echo Linking $@
	@$(CC) -mcrt=$(CRT) -shared -Wl,-soname,$(TARGET_SHARED) -o $(TARGET_SHARED) $(OBJECTS) $(MAIN_OBJECT)

clean:
	@echo Cleaning
	@rm -f $(TARGET_STATIC) $(TARGET_SHARED) $(TESTLIB_STATIC) $(ALL_OBJECTS) $(PREFS_PROGRAM) $(DEPS) libSDL2main.a
	make -C test -fMakefile.amigaos3 clean

install:
	mkdir -p $(PATH_TO_TOOLS)/include/SDL2
	cp include/* $(PATH_TO_TOOLS)/include/SDL2
	cp libSDL2*.a $(PATH_TO_TOOLS)/lib

%.o : %.c
	@echo Compiling $<
	@$(CC) -o $@ -c $< $(CFLAGS)

%.d : %.c
	@echo Making dependencies for $<
	@$(CC) -MM -MP -MT $(@:.d=.o) -o $@ $< $(CFLAGS)

# Load .d files
ifneq ($(MAKECMDGOALS),clean)
-include $(DEPS)
endif
